### ISSUE TITLE
Missing closing bracket

### ISSUE THREAD

**Issue by albmed** [pokerth/pokerth-live#1]
Hi, 
I think there is a missing closing bracket in file neteventhandler.js: looks there is no closing bracket for `switch ` in line 147. 

If I'm not wrong lines 206-210 should be: 

```
			case PokerTH.GameMessage.GameMessageType.Type_TimeoutWarningMessage :
				self.handleMsgTimeoutWarning(gameMessage.timeoutWarningMessage);
				break;
			} // <-- This is the missing bracket. 
		}
	};

```
Regards,
Albert.

**Comment by lotodore** [comment]
Please use the stable branch for now, the master branch contains unfinished code (had to stop in the middle of coding).

**Comment by albmed** [comment]
Sorry, didn't realize branches were different regarding that file.
